### ISSUE TITLE
http: exit informally

### ISSUE THREAD

**Issue by lolBig** [yodaos-project/ShadowNode#369] opened 2018-10-10 22:03 UTC
```js
var http = require('http');
var https = require('https');

function getHandle(url) {
  if (/^http:\/\//.test(url)) {
    return http;
  } else if (/^https:\/\//.test(url)) {
    return https;
  }
  throw new Error('unsupported url ' + url);
}

// test http_client
test('https://127.0.0.1/');
// test https_client
test('https://127.0.0.1/');

function test(url) {
  var handle = getHandle(url);
  var req = handle.get(url, function() {});
  req.end();
  return req;
}

```

exit with one of below errors:
1. `./src/iotjs_binding_helper.c:36: Assertion 'jerry_value_is_function(jonuncaughtexception)' failed.`
2. `./src/iotjs_binding.c:230: Assertion 'jerry_value_is_object(jobj)' failed.`

**Comment by yorkie** [comment] 2019-09-26 07:49
Cannot reproduce this bug for now, just closing it :)

**Closed by yorkie** 2019-09-26 07:49 UTC
Labels: bug, http, https
